import '@/styles/globals.css'
import { Providers } from './providers'
import StoreProvider from '@/stores/provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="min-h-screen bg-background font-sans antialiased">
        <StoreProvider>
          <Providers>
            <div className="relative flex flex-col h-screen">
              <main className="container mx-auto max-w-7xl pt-16 px-6 flex-grow">
                {children}
              </main>
            </div>
          </Providers>
        </StoreProvider>
      </body>
    </html>
  )
}
